import 'package:cloud_firestore/cloud_firestore.dart';

import '../data/urge_needs.dart';
import '../data/urge_types.dart';

/// Lifecycle state of one Urge Rescue session.
///
/// A session is different from an [UrgeModel]:
/// - UrgeModel = a historical urge/event.
/// - UrgeSessionModel = the complete rescue journey around that urge.
///
/// The session lets ReWireX learn whether an intervention actually helped.
enum UrgeSessionStatus {
  started,
  interventionSelected,
  inProgress,
  rechecked,
  completed,
  escalated,
  abandoned,
}

extension UrgeSessionStatusX on UrgeSessionStatus {
  String get key => switch (this) {
        UrgeSessionStatus.started => 'started',
        UrgeSessionStatus.interventionSelected => 'intervention_selected',
        UrgeSessionStatus.inProgress => 'in_progress',
        UrgeSessionStatus.rechecked => 'rechecked',
        UrgeSessionStatus.completed => 'completed',
        UrgeSessionStatus.escalated => 'escalated',
        UrgeSessionStatus.abandoned => 'abandoned',
      };

  static UrgeSessionStatus fromKey(String? value) {
    final key = value?.trim().toLowerCase();

    for (final status in UrgeSessionStatus.values) {
      if (status.key == key) return status;
    }

    return UrgeSessionStatus.started;
  }
}

/// Result of the post-intervention urge recheck.
enum UrgeOutcome {
  resolved,
  reduced,
  unchanged,
  stronger,
  escalated,
  unknown,
}

extension UrgeOutcomeX on UrgeOutcome {
  String get key => switch (this) {
        UrgeOutcome.resolved => 'resolved',
        UrgeOutcome.reduced => 'reduced',
        UrgeOutcome.unchanged => 'unchanged',
        UrgeOutcome.stronger => 'stronger',
        UrgeOutcome.escalated => 'escalated',
        UrgeOutcome.unknown => 'unknown',
      };

  String get label => switch (this) {
        UrgeOutcome.resolved => 'Urge mostly gone',
        UrgeOutcome.reduced => 'Urge is lower',
        UrgeOutcome.unchanged => 'Urge feels about the same',
        UrgeOutcome.stronger => 'Urge became stronger',
        UrgeOutcome.escalated => 'I need more support',
        UrgeOutcome.unknown => 'Not recorded',
      };

  static UrgeOutcome fromKey(String? value) {
    final key = value?.trim().toLowerCase();

    for (final outcome in UrgeOutcome.values) {
      if (outcome.key == key) return outcome;
    }

    return UrgeOutcome.unknown;
  }
}

/// A single Urge Rescue journey.
///
/// Example:
///
///   Trigger:      Argument / conflict
///   Emotion:      Angry
///   Urge:         sendAngryMessage
///   Need:         validation
///   Intervention: message_shield
///   Before:       8
///   After:        3
///   Outcome:      reduced
///
/// This model is intentionally independent from UI widgets so that the same
/// rescue session can later be used by:
/// - the Rescue screens,
/// - AI Coach,
/// - analytics,
/// - prediction/risk systems,
/// - intervention personalization.
class UrgeSessionModel {
  final String id;
  final String userId;

  /// User's selected/derived action impulse.
  final UrgeType urgeType;

  /// Emotion is kept as a free/stable label for compatibility with the
  /// existing urge system, which currently stores emotions as strings.
  final String emotion;

  /// Trigger that led into this session.
  final String trigger;

  /// User's context/environment.
  final String context;

  /// Optional physical sensation captured during the urge.
  final String bodyLocation;

  /// The need selected by the user or suggested by the routing engine.
  final NeedType? selectedNeed;

  /// Ordered candidate needs generated by the routing engine.
  final List<NeedType> suggestedNeeds;

  /// The rescue family selected by the router.
  final UrgeRescuePath rescuePath;

  /// Stable identifier of the exact intervention selected from the
  /// intervention catalog.
  final String? interventionId;

  /// Human-readable intervention title, cached for history/analytics so that
  /// old sessions remain understandable if catalog copy changes later.
  final String? interventionTitle;

  /// Initial urge score. Kept separate from emotion intensity.
  ///
  /// Range is normally 1..10.
  final int? urgeBefore;

  /// Post-intervention urge score.
  ///
  /// Range is normally 0..10 where 0 means the urge is gone.
  final int? urgeAfter;

  /// User-selected outcome after the rescue/recheck.
  final UrgeOutcome outcome;

  final UrgeSessionStatus status;

  /// Free-form notes supplied during the rescue flow.
  final String notes;

  /// Whether the selected intervention was actually completed.
  final bool interventionCompleted;

  /// Whether the session required escalation to Connect/Crisis/Safety flows.
  final bool wasEscalated;

  final DateTime startedAt;
  final DateTime? interventionStartedAt;
  final DateTime? interventionCompletedAt;
  final DateTime? recheckedAt;
  final DateTime? completedAt;
  final DateTime updatedAt;

  /// Computed duration from the stored timestamps.
  Duration? get duration {
    final end = completedAt ?? recheckedAt ?? interventionCompletedAt;
    if (end == null) return null;

    final value = end.difference(startedAt);
    return value.isNegative ? Duration.zero : value;
  }

  const UrgeSessionModel({
    required this.id,
    required this.userId,
    required this.urgeType,
    required this.emotion,
    required this.trigger,
    required this.context,
    required this.bodyLocation,
    required this.selectedNeed,
    required this.suggestedNeeds,
    required this.rescuePath,
    required this.interventionId,
    required this.interventionTitle,
    required this.urgeBefore,
    required this.urgeAfter,
    required this.outcome,
    required this.status,
    required this.notes,
    required this.interventionCompleted,
    required this.wasEscalated,
    required this.startedAt,
    required this.interventionStartedAt,
    required this.interventionCompletedAt,
    required this.recheckedAt,
    required this.completedAt,
    required this.updatedAt,
  });

  /// Creates a new rescue session.
  factory UrgeSessionModel.start({
    required String id,
    required String userId,
    required UrgeType urgeType,
    String emotion = '',
    String trigger = '',
    String context = '',
    String bodyLocation = '',
    int? urgeBefore,
    List<NeedType> suggestedNeeds = const [],
    DateTime? startedAt,
  }) {
    final now = startedAt ?? DateTime.now();

    return UrgeSessionModel(
      id: id,
      userId: userId,
      urgeType: urgeType,
      emotion: emotion,
      trigger: trigger,
      context: context,
      bodyLocation: bodyLocation,
      selectedNeed: null,
      suggestedNeeds: List.unmodifiable(suggestedNeeds),
      rescuePath: urgeType.defaultRescuePath,
      interventionId: null,
      interventionTitle: null,
      urgeBefore: _clampScore(urgeBefore, min: 1, max: 10),
      urgeAfter: null,
      outcome: UrgeOutcome.unknown,
      status: UrgeSessionStatus.started,
      notes: '',
      interventionCompleted: false,
      wasEscalated: false,
      startedAt: now,
      interventionStartedAt: null,
      interventionCompletedAt: null,
      recheckedAt: null,
      completedAt: null,
      updatedAt: now,
    );
  }

  /// Returns a copy with selected rescue information updated.
  UrgeSessionModel copyWith({
    String? id,
    String? userId,
    UrgeType? urgeType,
    String? emotion,
    String? trigger,
    String? context,
    String? bodyLocation,
    bool clearSelectedNeed = false,
    NeedType? selectedNeed,
    List<NeedType>? suggestedNeeds,
    UrgeRescuePath? rescuePath,
    bool clearInterventionId = false,
    String? interventionId,
    bool clearInterventionTitle = false,
    String? interventionTitle,
    int? urgeBefore,
    bool clearUrgeBefore = false,
    int? urgeAfter,
    bool clearUrgeAfter = false,
    UrgeOutcome? outcome,
    UrgeSessionStatus? status,
    String? notes,
    bool? interventionCompleted,
    bool? wasEscalated,
    DateTime? startedAt,
    DateTime? interventionStartedAt,
    bool clearInterventionStartedAt = false,
    DateTime? interventionCompletedAt,
    bool clearInterventionCompletedAt = false,
    DateTime? recheckedAt,
    bool clearRecheckedAt = false,
    DateTime? completedAt,
    bool clearCompletedAt = false,
    DateTime? updatedAt,
  }) {
    return UrgeSessionModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      urgeType: urgeType ?? this.urgeType,
      emotion: emotion ?? this.emotion,
      trigger: trigger ?? this.trigger,
      context: context ?? this.context,
      bodyLocation: bodyLocation ?? this.bodyLocation,
      selectedNeed:
          clearSelectedNeed ? null : selectedNeed ?? this.selectedNeed,
      suggestedNeeds:
          List.unmodifiable(suggestedNeeds ?? this.suggestedNeeds),
      rescuePath: rescuePath ?? this.rescuePath,
      interventionId: clearInterventionId
          ? null
          : interventionId ?? this.interventionId,
      interventionTitle: clearInterventionTitle
          ? null
          : interventionTitle ?? this.interventionTitle,
      urgeBefore: clearUrgeBefore
          ? null
          : urgeBefore ?? this.urgeBefore,
      urgeAfter: clearUrgeAfter ? null : urgeAfter ?? this.urgeAfter,
      outcome: outcome ?? this.outcome,
      status: status ?? this.status,
      notes: notes ?? this.notes,
      interventionCompleted:
          interventionCompleted ?? this.interventionCompleted,
      wasEscalated: wasEscalated ?? this.wasEscalated,
      startedAt: startedAt ?? this.startedAt,
      interventionStartedAt: clearInterventionStartedAt
          ? null
          : interventionStartedAt ?? this.interventionStartedAt,
      interventionCompletedAt: clearInterventionCompletedAt
          ? null
          : interventionCompletedAt ?? this.interventionCompletedAt,
      recheckedAt:
          clearRecheckedAt ? null : recheckedAt ?? this.recheckedAt,
      completedAt:
          clearCompletedAt ? null : completedAt ?? this.completedAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Persisted Firestore representation.
  ///
  /// Enum values are stored through stable keys instead of enum.name so
  /// future Dart enum renames do not silently break stored data.
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'urgeType': urgeType.key,
      'emotion': emotion,
      'trigger': trigger,
      'context': context,
      'bodyLocation': bodyLocation,
      'selectedNeed': selectedNeed?.key,
      'suggestedNeeds': suggestedNeeds.map((e) => e.key).toList(),
      'rescuePath': rescuePath.key,
      'interventionId': interventionId,
      'interventionTitle': interventionTitle,
      'urgeBefore': urgeBefore,
      'urgeAfter': urgeAfter,
      'outcome': outcome.key,
      'status': status.key,
      'notes': notes,
      'interventionCompleted': interventionCompleted,
      'wasEscalated': wasEscalated,
      'startedAt': Timestamp.fromDate(startedAt),
      'interventionStartedAt': _timestampOrNull(interventionStartedAt),
      'interventionCompletedAt': _timestampOrNull(interventionCompletedAt),
      'recheckedAt': _timestampOrNull(recheckedAt),
      'completedAt': _timestampOrNull(completedAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
    };
  }

  /// Firestore representation for an update where [updatedAt] should be
  /// server-authoritative.
  Map<String, dynamic> toServerUpdateMap() {
    final map = toMap();
    map['updatedAt'] = FieldValue.serverTimestamp();
    return map;
  }

  factory UrgeSessionModel.fromMap(
    String id,
    Map<String, dynamic> map,
  ) {
    final suggestedRaw = map['suggestedNeeds'];

    final suggested = <NeedType>[];
    if (suggestedRaw is Iterable) {
      for (final value in suggestedRaw) {
        suggested.add(NeedTypeX.fromKey(value?.toString()));
      }
    }

    final startedAt = _readDate(
          map['startedAt'],
          fallback: DateTime.now(),
        ) ??
        DateTime.now();

    return UrgeSessionModel(
      id: id,
      userId: map['userId']?.toString() ?? '',
      urgeType: UrgeTypeX.fromKey(
        map['urgeType']?.toString() ?? map['type']?.toString(),
      ),
      emotion: map['emotion']?.toString() ?? '',
      trigger: map['trigger']?.toString() ?? '',
      context: map['context']?.toString() ?? '',
      bodyLocation: map['bodyLocation']?.toString() ?? '',
      selectedNeed: map['selectedNeed'] == null
          ? null
          : NeedTypeX.fromKey(map['selectedNeed'].toString()),
      suggestedNeeds: List.unmodifiable(suggested),
      rescuePath: UrgeRescuePathX.fromKey(
        map['rescuePath']?.toString(),
      ),
      interventionId: _nullableString(map['interventionId']),
      interventionTitle: _nullableString(map['interventionTitle']),
      urgeBefore: _readScore(map['urgeBefore'], min: 1, max: 10),
      urgeAfter: _readScore(map['urgeAfter'], min: 0, max: 10),
      outcome: UrgeOutcomeX.fromKey(map['outcome']?.toString()),
      status: UrgeSessionStatusX.fromKey(map['status']?.toString()),
      notes: map['notes']?.toString() ?? '',
      interventionCompleted:
          map['interventionCompleted'] as bool? ?? false,
      wasEscalated: map['wasEscalated'] as bool? ?? false,
      startedAt: startedAt,
      interventionStartedAt: _readDate(map['interventionStartedAt']),
      interventionCompletedAt:
          _readDate(map['interventionCompletedAt']),
      recheckedAt: _readDate(map['recheckedAt']),
      completedAt: _readDate(map['completedAt']),
      updatedAt: _readDate(map['updatedAt']) ?? startedAt,
    );
  }

  /// Generates an outcome from before/after urge scores.
  ///
  /// Score 0 is allowed only after the rescue/recheck because it means the
  /// urge is no longer felt.
  static UrgeOutcome outcomeFromScores(int before, int after) {
  final b = before.clamp(1, 10);
  final a = after.clamp(0, 10);

  if (a == 0) return UrgeOutcome.resolved;
  if (a < b) return UrgeOutcome.reduced;
  if (a == b) return UrgeOutcome.unchanged;
  return UrgeOutcome.stronger;
}

  /// Returns a 0..1 effectiveness score for analytics.
  ///
  /// 1.0 = urge completely resolved
  /// 0.0 = no improvement or stronger
  double get effectivenessScore {
    final before = urgeBefore;
    final after = urgeAfter;

    if (before == null || after == null || before <= 0) return 0.0;

    final reduction = (before - after) / before;
    return reduction.clamp(0.0, 1.0);
  }

  static Timestamp? _timestampOrNull(DateTime? value) {
    return value == null ? null : Timestamp.fromDate(value);
  }

  static String? _nullableString(dynamic value) {
    final text = value?.toString().trim();
    return text == null || text.isEmpty ? null : text;
  }

  static DateTime? _readDate(
    dynamic value, {
    DateTime? fallback,
  }) {
    if (value == null) return fallback;

    if (value is Timestamp) {
      return value.toDate();
    }

    if (value is DateTime) {
      return value;
    }

    if (value is int) {
      return DateTime.fromMillisecondsSinceEpoch(value);
    }

    // Supports Firestore-compatible Timestamp-like objects and legacy data.
    try {
      final dynamic converted = (value as dynamic).toDate();
      if (converted is DateTime) return converted;
    } catch (_) {
      // Ignore malformed timestamp and use fallback.
    }

    return fallback;
  }

  static int? _readScore(
    dynamic value, {
    required int min,
    required int max,
  }) {
    if (value == null) return null;

    final number = value is num
        ? value.toInt()
        : int.tryParse(value.toString());

    if (number == null) return null;

    return number.clamp(min, max);
  }

  static int? _clampScore(
    int? value, {
    required int min,
    required int max,
  }) {
    if (value == null) return null;
    return value.clamp(min, max);
  }
}
