// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn05yFphtR852ebTrpOl_P5rcfI0-7FgQ',
    appId: '1:1054000063885:web:2d505384da910ed563c9c4',
    messagingSenderId: '1054000063885',
    projectId: 'rewirex-c639d',
    authDomain: 'rewirex-c639d.firebaseapp.com',
    storageBucket: 'rewirex-c639d.firebasestorage.app',
    measurementId: 'G-Y19M1MJDSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoj7TfgpRKeCip8_GWcknFNCJHTAT9yTw',
    appId: '1:1054000063885:android:c8914b7a30c3295e63c9c4',
    messagingSenderId: '1054000063885',
    projectId: 'rewirex-c639d',
    storageBucket: 'rewirex-c639d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRj6jPooLVcmUDN2hy2nDjx1WRvJT3HDE',
    appId: '1:1054000063885:ios:7757441d4347aaea63c9c4',
    messagingSenderId: '1054000063885',
    projectId: 'rewirex-c639d',
    storageBucket: 'rewirex-c639d.firebasestorage.app',
    iosBundleId: 'com.example.rewirex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRj6jPooLVcmUDN2hy2nDjx1WRvJT3HDE',
    appId: '1:1054000063885:ios:7757441d4347aaea63c9c4',
    messagingSenderId: '1054000063885',
    projectId: 'rewirex-c639d',
    storageBucket: 'rewirex-c639d.firebasestorage.app',
    iosBundleId: 'com.example.rewirex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn05yFphtR852ebTrpOl_P5rcfI0-7FgQ',
    appId: '1:1054000063885:web:a5823a9308b3adf263c9c4',
    messagingSenderId: '1054000063885',
    projectId: 'rewirex-c639d',
    authDomain: 'rewirex-c639d.firebaseapp.com',
    storageBucket: 'rewirex-c639d.firebasestorage.app',
    measurementId: 'G-66J38BHXTG',
  );

}